@baseUrl = http://localhost:3000
@contentType = application/json

### Create an Account
POST {{baseUrl}}/signup
Content-Type: {{contentType}}

{
    "firstName":"Teste",
    "lastName":"Teste",
    "email":"teste@teste.com.br"
}